[build-system]
requires = [
    "robotpy-build<2023,>=2022.2.0",
    "wpilib<2023.0.0,>=2022.2.1.3",
]

[tool.robotpy-build]
base_package = "photonvision"

[tool.robotpy-build.wrappers."photonvision".maven_lib_download]
artifact_id = "PhotonLib-cpp"
group_id = "org.photonvision"
repo_url = "https://maven.photonvision.org/repository/internal/"
version = "v2023.1.1-beta-6"

libs = ["Photon"]

[tool.robotpy-build.wrappers."photonvision"]
name = "photonvision"

depends = ["wpilibc", "wpimath_geometry", "wpimath_cpp", "ntcore", "wpiHal", "wpiutil"]

sources = [
    "photonvision/src/module.cpp",
]

generation_data = "gen"

[tool.robotpy-build.wrappers."photonvision".autogen_headers]
# photonlib
Packet = "photonlib/Packet.h"
PhotonCamera = "photonlib/PhotonCamera.h"
PhotonPipelineResult = "photonlib/PhotonPipelineResult.h"
PhotonTrackedTarget = "photonlib/PhotonTrackedTarget.h"
PhotonUtils = "photonlib/PhotonUtils.h"

[tool.robotpy-build.metadata]
name = "robotpy-photonvision"
description = "RobotPy wrappers for photonvision"
author = "RobotPy Development Team"
author_email = "robotpy@googlegroups.com"
url = "https://github.com/robotpy/robotpy-photonvision"
license = "MIT"
install_requires = [
    "wpilib<2023.0.0,>=2022.2.1.3",
]
