[build-system]
requires = [
    "robotpy-build<2024,>=2023.0.0b17",
    "robotpy-wpimath<2024.0.0,>=2023.0.0b7",
    "wpilib<2024.0.0,>=2023.0.0b7",
]

[tool.robotpy-build.metadata]
name = "robotpy-photonvision"
description = "RobotPy wrappers for photonvision"
author = "RobotPy Development Team"
author_email = "robotpy@googlegroups.com"
url = "https://github.com/robotpy/robotpy-photonvision"
license = "MIT"
install_requires = [
    "robotpy-wpimath<2024.0.0,>=2023.0.0b7",
    "wpilib<2024.0.0,>=2023.0.0b7",
]

[tool.robotpy-build]
base_package = "photonvision"

[tool.robotpy-build.wrappers."photonvision".maven_lib_download]
artifact_id = "PhotonLib-cpp"
group_id = "org.photonvision"
repo_url = "https://maven.photonvision.org/repository/internal"
version = "v2023.1.1-beta-7"

libs = ["Photon"]

[tool.robotpy-build.wrappers."photonvision"]
name = "photonvision"

depends = ["wpilibc", "wpimath_geometry", "wpimath_cpp", "ntcore", "wpiHal", "wpiutil"]

sources = [
    "photonvision/src/module.cpp",
]

generation_data = "gen"

[tool.robotpy-build.wrappers."photonvision".autogen_headers]
# photonlib
Packet = "photonlib/Packet.h"
PhotonCamera = "photonlib/PhotonCamera.h"
PhotonPipelineResult = "photonlib/PhotonPipelineResult.h"
PhotonTargetSortMode = "photonlib/PhotonTargetSortMode.h"
PhotonTrackedTarget = "photonlib/PhotonTrackedTarget.h"
PhotonUtils = "photonlib/PhotonUtils.h"
RobotPoseEstimator = "photonlib/RobotPoseEstimator.h"
SimPhotonCamera = "photonlib/SimPhotonCamera.h"
SimVisionSystem = "photonlib/SimVisionSystem.h"
SimVisionTarget = "photonlib/SimVisionTarget.h"
