[build-system]
requires = [
    "robotpy-build<2024,>=2023.0.0",
    "pyntcore~=2023.3.2",
    "robotpy-apriltag~=2023.3.2",
    "robotpy-wpimath~=2023.3.2",
    "wpilib~=2023.3.2",
]

[tool.robotpy-build.metadata]
name = "robotpy-photonvision"
description = "RobotPy wrappers for photonvision"
author = "RobotPy Development Team"
author_email = "robotpy@googlegroups.com"
url = "https://github.com/robotpy/robotpy-photonvision"
license = "MIT"
install_requires = [
    "pyntcore<2024.0.0,>=2023.3.2",
    "robotpy-apriltag<2024.0.0,>=2023.3.2",
    "robotpy-wpimath<2024.0.0,>=2023.3.2",
    "wpilib<2024.0.0,>=2023.3.2",
]

[tool.robotpy-build]
base_package = "photonvision"

[tool.robotpy-build.wrappers."photonvision".maven_lib_download]
artifact_id = "PhotonLib-cpp"
group_id = "org.photonvision"
repo_url = "https://maven.photonvision.org/repository/snapshots"
version = "dev-v2023.3.0-8-g3edc8750"

use_sources = true
sources = [
    "photonlib/PhotonCamera.cpp",
    "photonlib/PhotonPipelineResult.cpp",
    "photonlib/PhotonPoseEstimator.cpp",
    "photonlib/PhotonTrackedTarget.cpp",
    "photonlib/RobotPoseEstimator.cpp",
]

[[tool.robotpy-build.wrappers."photonvision".maven_lib_download.patches]]
patch = "photonvision/src/sources.patch"

[[tool.robotpy-build.wrappers."photonvision".maven_lib_download.header_patches]]
patch = "photonvision/src/headers.patch"

[tool.robotpy-build.wrappers."photonvision"]
name = "photonvision"

depends = [
    "apriltag",
    "wpilibc",
    "wpimath_geometry",
    "wpimath_cpp",
    "ntcore",
    "wpiHal",
    "wpiutil",
]

sources = [
    "photonvision/src/module.cpp",
]

generation_data = "gen"

[tool.robotpy-build.wrappers."photonvision".autogen_headers]
# photonlib
Packet = "photonlib/Packet.h"
PhotonCamera = "photonlib/PhotonCamera.h"
PhotonPipelineResult = "photonlib/PhotonPipelineResult.h"
PhotonPoseEstimator = "photonlib/PhotonPoseEstimator.h"
PhotonTargetSortMode = "photonlib/PhotonTargetSortMode.h"
PhotonTrackedTarget = "photonlib/PhotonTrackedTarget.h"
PhotonUtils = "photonlib/PhotonUtils.h"
RobotPoseEstimator = "photonlib/RobotPoseEstimator.h"
SimPhotonCamera = "photonlib/SimPhotonCamera.h"
SimVisionSystem = "photonlib/SimVisionSystem.h"
SimVisionTarget = "photonlib/SimVisionTarget.h"
